FROM node:16-alpine

WORKDIR /zed-e2e-test

COPY package.json /zed-e2e-test/
COPY package-lock.json /zed-e2e-test/

RUN npm ci
RUN npx playwright install chromium

COPY src/. /zed-e2e-test/src/

CMD npx playwright test src/trading-test --config=src/trading-test/trading-test.config.js
